#+TITLE: Measure
#+AUTHOR: Parth Shimpi
#+STARTUP: latexpreview indent

* Algebras and Measures

** Set functions 

Does every subset of \(\mathbb{R}^n\) have a 'volume'? What we require is a non-negative valued function on the powerset \(2^{\mathbb{R}^n}\) that behaves nicely like a volume-measure should. Sadly, this is not possible (as we will see), and best we can do is define such a volume-measure on special subsets of \(\mathbb{R}^n\). More generally, our question is about what set functions we are allowed to define, and how they behave.

DEFINITION For \(\mathcal{A}\subset 2^A\) with \(\emptyset \in \mathcal{A}\), \(\mu: \mathcal{A}\rightarrow [0,+\infty]\) is a /set function/ on \(A\) if \(\mu(\emptyset) = 0\).

    Say \(\mu\) is finitely (resp. countably) /additive/ if for finite (resp. countable) collections \(\{A_i\}\subset \mathcal{A}\) of disjoint sets, \(\mu(\coprod A_i) = \sum \mu(A_i)\) whenever defined.

    \(\mu\) is finitely (resp. countably) /subadditive/ if for finite (resp. countable) collections \(\{A_i\}\subset \mathcal{A}\) of sets, \(\mu(\bigcup A_i)\leq \sum \mu(A_i)\) whenever defined.

    \(\mu\) is /increasing/ if \(A\subset B \; \Rightarrow \; \mu(A)\leq \mu(B)\). 

    \(\mu\) has /upward monotone convergence/ if for any collection \(A_1 \subset A_2 \subset A_3 \subset ...\) of nested subsets, we have \(\mu(A_i) \rightarrow \mu(\bigcup_i A_i) = \sup \mu(A_i)\). 

    Similarly, \(\mu\) has /downward monotone convergence/ if for any collection \(A_1 \supset A_2 \supset A_3 \supset ...\) of nested subsets with finite measure, we have \(\mu(A_i) \rightarrow \mu(\bigcap_i A_i) = \inf \mu(A_i)\).

        Note that we require the finite measure assumption to allow cases like \((n,\infty)\) where a collection of nested infinite sets have empty intersection.
        
** Collections of subsets

We need collections of subsets to define our set-functions on. When measuring volumes in \(\mathbb{R}^3\), it is natural to consider all subsets that can be written as finite unions of boxes, since the volumes of those are easiest to define. Such collections form an /algebra/.

*** Boolean algebras and Means 

DEFINITION A /boolean algebra/ on \(A\) is a subset of \(2^A\) containing \(\emptyset\) that is closed under taking complements and finite unions.

    Boolean algebras are automatically closed under taking finite intersections, set-differences and symmetric differences.

    DEFINITION For \(A\) a set and \(\mathcal{A} \subset 2^A\), the /boolean algebra generated by \(\mathcal{A}\)/ is the smallest boolean algebra \(\text{b}(\mathcal{A})\) containing \(\mathcal{A}\), or the intersection of all boolean algebras containing \(\mathcal{A}\). This admits a nice description- \(\text{b}(\mathcal{A})\) is the collection of all finite unions and intersections of elements of \(\mathcal{A}\) and their complements.

        For instance, the boolean algebra generated by the topology on a set is the /algebra of constructible sets/, i.e. sets that are locally closed (closed in an open subspace, i.e. of the form \(\text{open} \cap \text{closed}\)).

DEFINITION For \(A\) a set and \(\mathcal{A}\subset 2^A\) a boolean algebra, a /mean/ on \((A,\mathcal{A})\) is a finitely additive set function \(m\) on \(A\).

    A mean is always finitely subadditive and increasing.

Then we can measure the volumes of a large chunk of subsets of \(\mathbb{R}^n\) by considering the natural mean \(m\) on the boolean algebra generated by boxes. Call such a set /elementary/. Then we can in fact extend \(m\) to more than just elementary sets, by allowing things that they limit to: a subset \(A\subset \mathbb{R}^n\) is /Jordan-measurable/ if for any \(\epsilon>0\) there are elementary sets \(E \subset A \subset F\) such that \(m(F\setminus E) < \epsilon\). The collection of all Jordan-measurable subsets is again a boolean algebra, and \(m\) is a mean on it.

    The boolean algebra of Jordan-measurable sets is genuinely bigger than the one of elementary sets. For instance, the \(n\)-sphere is not a finite union of boxes, but is still Jordan-measurable. (TODO Prove?) 

    The Jordan measure is reminiscent of the Riemann integral, and the relation is in fact very strong: a subset of \(\mathbb{R}\) is Jordan-measurable if and only if its indicator function is Riemann integrable. (TODO Prove?) 

    There are also sets that are not Jordan-measurable, but have volumes in the traditional sense. In particular, Jordan-measurable sets are always bounded so something like Gabriel's horn (which has a finite volume in \(\mathbb{R}^3\)) is not Jordan-measurable. A bounded non-Jordan-measurable set is \(\mathbb{Q}\cap [0,1]\), since any elementary set containing it must have mean atleast \(1\) while any elementary set inside it must be finite hence having zero mean.

*** Sigma algebras and Measures 

One shortcoming boolean algebras have is that they are restricted to finite unions, whereas when thinking of volumes it is natural to consider limits of series: \(1 + \frac{1}{2} + \frac{1}{4} + ... = 2\). In the transition from elementary sets to Jordan-measurable ones, we essentially allowed only /some/ countable unions. Thus it makes sense to extend our definitions to /all/ countable unions. 

    In fact, countability is the furthest it makes sense to go, since the sum of uncountably many positive reals cannot be finite. We can consider algebras which include arbitrary unions, but then 'most' of the elements in the algebra would have infinite (or zero) volume and hence the information we get would be largely uninteresting. 

    THEOREM If we have a collection \(n_i \geq 0\) of reals with \(\sum_{i \in I}n_i < \infty\) then at most countably many \(n_i\) can be non-zero.
 
        SKETCH Let \(S_n = \{n_i | n_i > \frac{1}{n}\}\), for \(n \in \mathbb{N}\). If any \(S_n\) has infinitely many elements, then \(\sum_{i \in I}n_i > \sum_{m \in S_n} m= \infty\), hence each \(S_n\) is finite. Then the set of non-zero elements is \(\bigcup_{n\in \mathbb{N}}S_n\) which is a countable union of finite sets.

DEFINITION A /\(\sigma\)-algebra/ \(\mathcal{A}\) on \(A\) is a subset of \(2^A\) that contains \(\emptyset\) and is closed under taking complements and countable unions. The pair \((A,\mathcal{A})\) is called a /measurable space/, and each element of \(\mathcal{A}\) is a measurable set.

    \(\sigma\)-algebras are automatically closed under taking countable intersections, set differences and symmetric differences.

    DEFINITION For \(A\) a set and \(\mathcal{A}\subset 2^A\), the /\(\sigma\)-algebra generated by \(\mathcal{A}\)/ is the smallest \(\sigma\)-algebra \(\sigma(\mathcal{A})\) containing \(\mathcal{A}\), i.e. the intersection of all \(\sigma\)-algebras containing \(\mathcal{A}\).

        Unlike boolean algebras these admit no simple description, since taking countable unions and complements is not a straightforward procedure. For instance, the \(\sigma\)-algebra generated by the topology on a Polish (separable and metrizable) space \(X\) is called the /Borel \(\sigma\)-algebra/ \(\mathcal{B}(X)\). It is easy to see that this exists because the powerset itself is a \(\sigma\)-algebra containing the topology, but constructing it requires using transfinite induction to generate the /Borel Heirarchy/: 

        - \(\mathbf{\Sigma^0_1}\) is the collection of all open sets, \(\mathbf{\Pi}^0_1\) is the collection of all closed sets.
        - \(\mathbf{\Sigma}^0_\alpha\) for \(\alpha > 1\) is generated by taking countable unions of elements in \(\bigcup_{\beta < \alpha} \mathbf{\Pi}^0_\beta\). (Sets of this class are closed under countable unions.)
        - A set is in \(\mathbf{\Pi}^0_\alpha\) iff its complement is in \(\mathbf{\Sigma}^0_\alpha\). (Sets of this class are closed under countable intersections)
        - \(\mathbf{\Delta}^0_{\alpha} = \mathbf{\Sigma}^0_\alpha \cap \mathbf{\Pi}^0_\alpha\)
       
        Then \(\mathbf{\Delta}^0_{\omega_1}\) is the Borel \(\sigma\)-algebra on \(A\). (TODO Proof?)

DEFINITION A /measure/ on \((A,\mathcal{A})\) is a countably additive set function \(\mu\) on \(A\). The triple \((A,\mathcal{A},\mu)\) is called a /measure space/. 

    A measure is always countably subadditive and increasing, and has upward and downward monotone convergence.

*** Specifying the measure 

Since \(\sigma\)-algebras cannot be explicitly written down in non-trivial cases, specifying the measure on each measurable set is impossible. What we hope to do instead, is specify its value on a smaller collection of sets in a way that it can be extended to the whole \(\sigma\)-algebra in a unique way. Any boolean subalgebra works for instance, but that is overkill.
 
**** Uniqueness of the extension

Note that the extension given by Caratheodory need not be unique, for example consider the ring generated by half-open intervals \((a,b] \subset\mathbb{R}\). The pre-measure \(\mu((a,b])=\infty\) can be extended by either letting everything have infinite measure, or by letting the measure of a set be the number of points in it. This is however, the worst it gets.

DEFINITION A set-function \(\mu\) on \(A\) is /\(\sigma\)-finite/ (countably finite) if \(A\) can be written as a countable union of \(\mu\)-finite sets. 

As we will see, countably finite pre-measures can be uniquely determined by their action on rings. In fact, they are uniquely determined by their action on even simpler structures, and we try to answer the more general question of /how many sets should I check before I can conclude two measures are the same?/

    Trivially, you can conclude that two measures are the same if their actions coincide on the entire \(\sigma\)-algebra. However, this is unnecessary: if you know two measures coincide on a countable collection of disjoint sets then they must coincide on the union. Similarly if you know two measures agree on \(X\) and \(Y \supset X\) then they must agree on \(Y\setminus X\). Call the latter property /closure under local complements/. (Non-standard terminology.) 

    DEFINITION \(\mathcal{A} \subset 2^A\) is a /\(d\)-system/ (or /Dynkin system/) if it contains \(A\) and is closed under taking local complements and countable disjoint unions.

        In particular, \(d\)-systems are closed under taking complements. They are also closed under taking unions of upwards-nested sequences, i.e. if \(X_1 \subset X_2 \subset X_3 \subset ...\) are in \(\mathcal{A}\) then so is \(\bigcup X_i\).  

        The upward-nested restatement is very nice because we can say a \(d\)-system is closed under countable union if and only if it is closed under finite union (or finite intersection, since we have complements.) In particular we have this: 

        LEMMA A family of subsets is a \(\sigma\)-algebra if and only if it is a \(d\)-system closed under finite intersections.

    Checking two measures coincide on intersections is necessary because knowing the measures of two sets does not uniquely determine the measure of their intersections. 

    DEFINITION \(\mathcal{A} \subset 2^A\) is a /\(\pi\)-system/ of it contains \(\emptyset\) and is closed under finite intersections.

    Intuitively, \(d\)-systems and \(\pi\)-systems capture the ideas of /overkill/ compared to /necessary/. This is also reflected in the requirements- \(d\) systems must contain the whole set (whose measure is ensured to be determined by \(\sigma\)-finiteness), while \(\pi\)-systems contain \(\emptyset\) (where two measures absolutely must coincide, to even qualify as measures.) 

    We just saw that \(\pi\)-closures of \(d\)-systems are always \(\sigma\)-algebras. The converse is true as well:

    LEMMA *(Dynkin's)* If \(\mathcal{A}\) is a \(\pi\)-system on \(A\), then any \(d\)-system containing \(\mathcal{A}\) also contains \(\sigma(\mathcal{A})\). 

        SKETCH We show that \(\mathcal{D}=\bigcap \{d\text{-systems containing }\mathcal{A}\}\) is itself a \(\sigma\)-algebra. It is clearly a \(d\)-system, and contains \(\mathcal{A}\). To show it is closed under finite intersections, consider \(\mathcal{D}' = \{D \in \mathcal{D}\;|\; D \cap X \in \mathcal{D} \quad \forall X \in \mathcal{D}\}\). This contains \(\mathcal{A}\): 

            To see this, look at \(\mathcal{D}'' = \{D \in \mathcal{D} \; | \; D \cap X \in \mathcal{D} \quad \forall X \in \mathcal{D}\}\). This is a \(d\)-system, and \(\mathcal{A}\) is a \(\pi\)-system so lies within \(\mathcal{D}''\). Then by the minimality of \(\mathcal{D}\), we have \(\mathcal{D}' = \mathcal{D}\).

        But \(\mathcal{D}'\) is also a \(d\)-system, so by the minimality of \(\mathcal{D}\) we have \(\mathcal{D}'' = \mathcal{D}\) which is hence closed under finite intersections. \(\square\)

    This sets us up for the main result, that knowing the values of a measure on a \(\pi\)-system is /sufficient/:
 
THEOREM Suppose \(\mu_1\) and \(\mu_2\) are \(\sigma\)-finite measures on a measurable space \((A,\mathcal{A})\) that agree on some \(\pi\)-system generating \(\mathcal{A}\). Then they agree on all of \(\mathcal{A}\).

DEFINITION A /ring/ \(\mathcal{A}\) on \(A\) is a subset of \(2^A\) containing \(\emptyset\) that is closed under finite unions and set-difference.

    Rings are closed under finite intersection and symmetric differences. In fact, \((\mathcal{A}, \Delta, \cap)\) is an algebraic ring with zero \(\emptyset\). Boolean algebras then correspond to rings with a unit (the set \(A\)).

    It is clear that every boolean algebra is a ring, but a ring need not contain the whole set. Intuitively, a ring cannot 'climb' to the topmost level (with just finite unions) while a boolean algebra can. For instance, all finite subsets of \(\mathbb{N}\) form a ring which isn't a boolean algebra.
